PR for t1, t2, images integration
notacodebro/LTRMPL-1201 pull request #2
Opened 2024-05-28 21:26 UTC by notacodebro

changes to diagrams
task1 complete
task 2 complete

remember do not delete this branch on merge

2024-05-29 11:25 UTC, blawrimore1 commented on task1/task1.md
> +```
need an 'end' to get from config mode to enable mode, then another 'config' to get back into config mode for the next section.

2024-05-29 11:29 UTC, blawrimore1 requested changes
one part in the ospf configuration process may need an edit.  comment added.

2024-05-29 13:20 UTC, blawrimore1 approved these changes

2024-05-30 11:53 UTC, notacodebro commented
merging pull post review

2024-05-30 11:53 UTC, merged